question_data = [
    {"category": "Animals",
     "type": "boolean",
     "difficulty": "easy",
     "question": "A slug&rsquo;s blood is green.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "The &#039;Squaring the Circle&#039; problem is solvable.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Salt is 100% composed of Sodium.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
